minor tweaks to maintanence scripts

diff --git a/salt/iiif/config/usr-local-bin-loris-cache-clean b/salt/iiif/config/usr-local-bin-loris-cache-clean
--- a/salt/iiif/config/usr-local-bin-loris-cache-clean
+++ b/salt/iiif/config/usr-local-bin-loris-cache-clean
@@ -1,10 +1,12 @@
 #!/bin/bash
-set -e
 # avoids race conditions by stopping the server before attempting to
 # clean files and folders in the caches
 # also, in case the occupied size is too high to safely execute 
 # loris-cache-clean in time, goes for the forest-burning loris-cache-purge
 # which deletes everything without taking LRU policies into consideration
+# run as root
+
+set -e
 
 if [ "$#" -lt 2 ]; then
     echo "Usage: loris-cache-clean SOFT_MAX_SIZE_KILOBYTES HARD_MAX_SIZE_KILOBYTES"
@@ -14,15 +16,12 @@ if [ "$#" -lt 2 ]; then
     exit 1
 fi
 
-LOG="/var/log/loris2/cache_clean.log"
-
 current_usage_cache_root () {
     df -k {{ pillar.iiif.loris.storage }} --output=used | sed 1d
 }
 
 log_message () {
-    echo -ne "$(date +[%c]) [loris-cache-clean] " >> "$LOG"
-    echo "$1" >> "$LOG"
+    logger "$1" --tag "loris-cache-clean"
 }
 
 log_message "Started loris-cache-clean (arguments $1 $2)"
@@ -35,17 +34,18 @@ log_message "Cache at $usage kb"
 if [ "$usage" -lt "$soft_limit" ]; then
     log_message "Nothing to do"
     exit 0
-elif [ "$usage" -lt "$hard_limit" ]; then
+fi
+
+systemctl stop nginx
+
+if [ "$usage" -lt "$hard_limit" ]; then
     log_message "Starting loris-cache-clean-soft"
-    /etc/init.d/nginx stop
-    timeout 240 /usr/local/bin/loris-cache-clean-soft "$soft_limit" || echo TIMEOUT OF loris-cache-clean-soft
-    /etc/init.d/nginx start
+    timeout 240 /usr/local/bin/loris-cache-clean-soft "$soft_limit" || log_message "TIMEOUT OF loris-cache-clean-soft"
     log_message "Completed loris-cache-clean-soft"
 else
     log_message "Starting loris-cache-clean-hard"
-    /etc/init.d/nginx stop
-    /usr/local/bin/loris-cache-clean-hard
-    /etc/init.d/nginx start
+    /usr/local/bin/loris-cache-clean-hard || log_message "FAILED loris-cache-clean-hard"
     log_message "Completed loris-cache-clean-hard"
 fi
 
+systemctl start nginx
